# Generated by Django 3.2.18 on 2023-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('1', 'Registration issue'), ('2', 'Login issue'), ('3', 'Delete Persona'), ('4', 'General Enquiry'), ('5', 'Report a comment'), ('6', 'Report a Persona')], default='4', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
                ('written_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
